Data:
  train_path: Data/raw/train.csv
  X_test_path: Data/raw/test.csv
  Y_test_path: Data/raw/prediction_submission.csv
  processed_path: Data/processed


Model:
  lgbm_save_path: src/artifacts/lgbm
  lgbm_report_path: src/artifacts/lgbm/report
  xgb_save_path: src/artifacts/xgb

Processor:
  Processor_path: src/artifacts

lgbm_shap:
  shap_save_path: src/artifacts/lgbm/shap